version: '3'

services:
  hlds-gameserver:
    build:
      context: .
      args:
        MOD: valve
    env_file: .env
    environment:
      PORT: 27016
      MAXPLAYERS: 32
      MAP: crossfire
      SERVER_NAME: My great halfLife server!
      SV_LAN: 0
      RCON_PASSWORD: ""
    ulimits: # Truncated core dumps fix
      core:
        soft: 1073741824 # 1GB
        hard: 1073741824 # 1GB
    ports:
      - $PORT:$PORT/udp
    expose:
      - $PORT/udp
    stdin_open: true
    tty: true
    entrypoint: "./hlds_run"
    command: ["\
        -debug \
        -game valve \
        +ip 0.0.0.0 \
        -port $PORT \
        +map $MAP \
        -maxplayers $MAXPLAYERS \
        +sv_lan $SV_LAN \
        +rcon_password \"$RCON_PASSWORD\" \
        +hostname \"$SERVER_NAME\"\
      "]

