name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - ".vscode/**"
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/hlds
  DOCKER_PLATFORMS: linux/amd64

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [steam_legacy, public]
        mod: [
          valve,
          cstrike
        ]
        include:
          - mod: valve
            depots: "1 4 1006"
          - mod: cstrike
            depots: "1 4 1006 11"

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.2.0

    - name: Cache Docker layers
      uses: actions/cache@v4.0.2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}-${{ matrix.branch }}-${{ matrix.mod }}
        restore-keys: ${{ runner.os }}-buildx-${{ matrix.branch }}-${{ matrix.mod }}

    - name: Log in to Docker Hub
      if: github.ref == 'refs/heads/master'
      uses: docker/login-action@v3.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: ./Dockerfile
        platforms: ${{ env.DOCKER_PLATFORMS }}
        push: ${{ github.ref == 'refs/heads/master' }}
        tags: ${{ env.DOCKER_IMAGE }}:${{ matrix.branch }}
        build-args: |
          APPBRANCH=${{ matrix.branch }}
          DEPOTS=${{ matrix.depots }}
          MOD=${{ matrix.mod }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache