name: Update Docker Hub Description

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/hlds

jobs:

  update_description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.DOCKER_IMAGE }}
          short-description: ${{ github.event.repository.description }}